# Generated by Django 2.0.2 on 2018-03-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.TextField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A'),
        ),
    ]
