# Generated by Django 2.0.1 on 2018-02-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20180222_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.TextField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A'),
        ),
    ]
